### ISSUE TITLE
install failed cause lwip2

### ISSUE THREAD

**Issue by SiriusGuo** [IonicaBizau/image-to-ascii#43]
I run **npm i --save image-to-ascii** and got an error:

> > node scripts/install.js
> 
> Installing lwip. If this fails, just install GraphicsMagick (http://www.graphicsmagick.org/).
> events.js:160
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: spawn npm ENOENT
>     at exports._errnoException (util.js:1036:11)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
>     at onErrorNT (internal/child_process.js:359:16)
>     at _combinedTickCallback (internal/process/next_tick.js:74:11)
>     at process._tickCallback (internal/process/next_tick.js:98:9)
>     at Module.runMain (module.js:592:11)
>     at run (bootstrap_node.js:394:7)
>     at startup (bootstrap_node.js:149:9)
>     at bootstrap_node.js:509:3
> npm ERR! Windows_NT 10.0.14393
> npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "--save" "image-to-ascii"
> npm ERR! node v6.6.0
> npm ERR! npm  v3.10.3
> npm ERR! code ELIFECYCLE
> 
> npm ERR! lwip2@1.0.3 install: `node scripts/install.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the lwip2@1.0.3 install script 'node scripts/install.js'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the lwip2 package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node scripts/install.js
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs lwip2
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls lwip2
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     D:\Code\npm-debug.log

and then run command **npm i --save lwip2** got the same error message even through the proxy. some thing wrong with my setting?

**Comment by SiriusGuo** [comment]
Sorry, my fault! 😅
