### ISSUE TITLE
[Windows] Install error

### ISSUE THREAD

**Issue by Keller18306** [IonicaBizau/image-to-ascii#69]
npm ERR! code 7
npm ERR! path C:\OpenServer\domains\justpro.local\CLI\nodejs\vktools\node_modules\lwip2
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node lib/install.js
npm ERR! Installing lwip. If this fails, just install GraphicsMagick (http://www.graphicsmagick.org/).
npm ERR! It seems like lwip failed to be intalled. Please check the errors.
npm ERR! npm WARN deprecated lodash-node@2.4.1: This package is discontinued. Use lodash@^4.0.0.
npm ERR! npm ERR! code 7
npm ERR! npm ERR! path C:\OpenServer\domains\justpro.local\CLI\nodejs\vktools\node_modules\lwip2\node_modules\lwip
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-gyp rebuild
npm ERR! npm ERR! gyp info it worked if it ends with ok
npm ERR! npm ERR! gyp info using node-gyp@3.8.0
npm ERR! npm ERR! gyp info using node@14.16.1 | win32 | x64
npm ERR! npm ERR! gyp info spawn C:\Python27\python.exe
npm ERR! npm ERR! gyp info spawn args [
npm ERR! npm ERR! gyp info spawn args   'C:\\OpenServer\\domains\\justpro.local\\CLI\\nodejs\\vktools\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! npm ERR! gyp info spawn args   '-f',
npm ERR! npm ERR! gyp info spawn args   'msvs',
npm ERR! npm ERR! gyp info spawn args   '-G',
npm ERR! npm ERR! gyp info spawn args   'msvs_version=2015',
npm ERR! npm ERR! gyp info spawn args   '-I',
npm ERR! npm ERR! gyp info spawn args   'C:\\OpenServer\\domains\\justpro.local\\CLI\\nodejs\\vktools\\node_modules\\lwip2\\node_modules\\lwip\\build\\config.gypi',
npm ERR! npm ERR! gyp info spawn args   '-I',
npm ERR! npm ERR! gyp info spawn args   'C:\\OpenServer\\domains\\justpro.local\\CLI\\nodejs\\vktools\\node_modules\\node-gyp\\addon.gypi',
npm ERR! npm ERR! gyp info spawn args   '-I',
npm ERR! npm ERR! gyp info spawn args   'C:\\Users\\kelle\\.node-gyp\\14.16.1\\include\\node\\common.gypi',
npm ERR! npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\kelle\\.node-gyp\\14.16.1',
npm ERR! npm ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\OpenServer\\domains\\justpro.local\\CLI\\nodejs\\vktools\\node_modules\\node-gyp',
npm ERR! npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\Users\\kelle\\.node-gyp\\14.16.1\\<(target_arch)\\node.lib',
npm ERR! npm ERR! gyp info spawn args   '-Dmodule_root_dir=C:\\OpenServer\\domains\\justpro.local\\CLI\\nodejs\\vktools\\node_modules\\lwip2\\node_modules\\lwip',
npm ERR! npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! npm ERR! gyp info spawn args   '--depth=.',
npm ERR! npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! npm ERR! gyp info spawn args   '--generator-output',
npm ERR! npm ERR! gyp info spawn args   'C:\\OpenServer\\domains\\justpro.local\\CLI\\nodejs\\vktools\\node_modules\\lwip2\\node_modules\\lwip\\build',
npm ERR! npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! npm ERR! gyp info spawn args ]
npm ERR! npm ERR! gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\Bin\MSBuild.exe
npm ERR! npm ERR! gyp info spawn args [
npm ERR! npm ERR! gyp info spawn args   'build/binding.sln',
npm ERR! npm ERR! gyp info spawn args   '/clp:Verbosity=minimal',
npm ERR! npm ERR! gyp info spawn args   '/nologo',
npm ERR! npm ERR! gyp info spawn args   '/p:Configuration=Release;Platform=x64'
npm ERR! npm ERR! gyp info spawn args ]
npm ERR! npm ERR! gyp ERR! UNCAUGHT EXCEPTION
npm ERR! npm ERR! gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\Bin\MSBuild.exe ENOENT
npm ERR! npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
npm ERR! npm ERR! gyp ERR! stack     at onErrorNT (internal/child_process.js:465:16)
npm ERR! npm ERR! gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:80:21)
npm ERR! npm ERR! gyp ERR! System Windows_NT 10.0.19042
npm ERR! npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\OpenServer\\domains\\justpro.local\\CLI\\nodejs\\vktools\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! npm ERR! gyp ERR! cwd C:\OpenServer\domains\justpro.local\CLI\nodejs\vktools\node_modules\lwip2\node_modules\lwip
npm ERR! npm ERR! gyp ERR! node -v v14.16.1
npm ERR! npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! npm ERR! gyp ERR! This is a bug in `node-gyp`.
npm ERR! npm ERR! gyp ERR! Try to update node-gyp and file an Issue if it does not help:
npm ERR! npm ERR! gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
npm ERR!
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     C:\Users\kelle\AppData\Local\npm-cache\_logs\2021-05-12T22_43_46_117Z-debug.log

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\kelle\AppData\Local\npm-cache\_logs\2021-05-12T22_43_46_372Z-debug.log

![image](https://user-images.githubusercontent.com/23178771/118053215-c8c3ca80-b38c-11eb-8a33-57656068ece5.png)
![image](https://user-images.githubusercontent.com/23178771/118053227-ce211500-b38c-11eb-9ca0-99d714c70ed5.png)

**Comment by Keller18306** [comment]
The bug was fixed by installing this:
https://sourceforge.net/projects/graphicsmagick/
